### PR TITLE
OE-361: Stack Trace error while Scheduling an Operation.

### PR DESCRIPTION
**Pull request by marshl**
Changed the afterSave() event of operation bookings to handle if the user hasn't specified a ward

### CODE REVIEW

**Comment by marshl** [comment]
To fix this issue, I also tried changing ward_id to be required, however there are quite a few instances of existing code that look like the following
```
<?php echo $operation->booking->ward ? $operation->booking->ward->longName : 'None'?>
```
This could mean that there are ways to add operation bookings without specifying a ward, so this seemed like the least risky way to fix the issue. TO simulate the SIT environment, I temporarily changed the dropdown list to have an empty array as the option set, and attempted the save. The save went through ok, and the resulting screen displayed ok too.

**Review by Vegemash — APPROVED** [review]

**Comment by Vegemash** [comment]
torololol

**Comment by Vegemash** [comment]
testing testing

**Comment by Vegemash** [comment]
doo wap

**Comment by Vegemash** [comment]
dap pa doo wap

**Comment by Vegemash** [comment]
culter

**Pull request merged**
