### PR TITLE
Fix/oea 458 print examination

### PR DESCRIPTION
**Pull request by Zhaolian-Zhou**
Fix the problem print PDF not work in firefox.
Download the PDF file directly.

### CODE REVIEW

**Review by apigram — APPROVED** [review]
This looks fine to me; however someone with Firefox & Edge will need to test this. I wasn't able to get my local OpenEyes to work on Edge so I'll leave that to either Liam or Isaac.

**Comment by Zhaolian-Zhou** [comment]
Can you also test print correspondence (OEA-420) when testing this, they are basically the same problem.

**Review by marshl — APPROVED** [review]
This does change the behaviour on Chrome, and I cannot get edge to contact my virtual machine, even my faster one, but it does work on Chrome and Firefox.

**Comment by marshl** [comment]
@apigram Did it work for you on IE11? I'm having difficulties saving an examination.

**Comment by marshl** [comment]
Can confirm, printing works fine on IE. I'm not sure why saving events isn't working, but it is an unrelated issue.

**Pull request merged**
